name = "10xflashcards"
compatibility_date = "2025-03-25"
main = "./dist/_worker.js/index.js"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "./dist" 

[observability.logs]
enabled = true